version: "2"
services:
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml